# -*- coding: utf-8 -*-
import json, urllib.request, urllib.error
base='http://localhost:8080/api/formations'
headers={'Content-Type':'application/json'}
formations=[
    {'title':'Developpement Web Moderne','description':'Apprenez a creer des applications web reactives avec React, Node.js et les meilleures pratiques modernes.','domain':'dev','level':'BEGINNER','duration':8,'price':25000.0,'image':'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2','rating':4.8,'reviews':34,'participants':120,'mode':'ONLINE','isActive':True,'objectives':['Comprendre le HTML/CSS/JS modernes','Maitriser React et les hooks','Deployer une application web'],'prerequisites':['Notions de programmation','Aimer le web'],'includes':['Projets concrets','Support de cours','Certificat de fin de formation'],'whatYouWillLearn':'Creer et deployer des applications web modernes utilisant React et Node.js.'},
    {'title':'Data Science et Machine Learning','description':'Devenez un expert en science des donnees avec Python, pandas, scikit-learn et des techniques de machine learning.','domain':'data','level':'INTERMEDIATE','duration':10,'price':32000.0,'image':'https://images.unsplash.com/photo-1517142089942-ba376ce32a2e','rating':4.7,'reviews':54,'participants':89,'mode':'HYBRID','isActive':True,'objectives':['Analyser des jeux de donnees','Construire des modeles predictifs','Visualiser les resultats'],'prerequisites':['Notions de Python','Statistiques de base'],'includes':['Datasets reels','Projets en groupe','Acces aux ressources'],'whatYouWillLearn':'Utiliser Python et machine learning pour resoudre des problemes data reels.'},
    {'title':'Design UX/UI pour debutants','description':'Apprenez a concevoir des interfaces utilisateur engageantes et ergonomiques pour applications web et mobiles.','domain':'design','level':'BEGINNER','duration':6,'price':22000.0,'image':'https://images.unsplash.com/photo-1498050108023-c5249f4df085','rating':4.9,'reviews':22,'participants':74,'mode':'ONLINE','isActive':True,'objectives':['Comprendre les principes UX','Maitriser le prototypage','Creer des interfaces attractives'],'prerequisites':['Curiosite pour le design'],'includes':['Templates Figma','Cas pratiques','Feedback personnalise'],'whatYouWillLearn':'Concevoir des experiences utilisateurs efficaces et belles.'},
    {'title':'Marketing Digital','description':'Maitrisez le marketing digital : SEO, publicite en ligne, reseaux sociaux et strategie de contenu pour booster votre presence en ligne.','domain':'marketing','level':'BEGINNER','duration':6,'price':20000.0,'image':'https://images.unsplash.com/photo-1460925895917-afdab827c52f','rating':4.6,'reviews':28,'participants':95,'mode':'ONLINE','isActive':True,'objectives':['Comprendre les fondamentaux du marketing digital','Maitriser le SEO et le SEM','Creer des campagnes publicitaires efficaces'],'prerequisites':['Aucun prerequis requis'],'includes':['Etudes de cas reels','Outils pratiques','Certificat de fin de formation'],'whatYouWillLearn':'Developper et executer une strategie marketing digitale complete.'},
    {'title':'Bureautique (Word, Excel, PowerPoint)','description':'Devenez un expert des outils bureautiques : Word pour le traitement de texte, Excel pour les tableaux et analyses, PowerPoint pour les presentations.','domain':'bureautique','level':'BEGINNER','duration':5,'price':15000.0,'image':'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5','rating':4.5,'reviews':45,'participants':150,'mode':'HYBRID','isActive':True,'objectives':['Maitriser Word pour la redaction','Utiliser Excel pour les calculs et analyses','Creer des presentations impactantes avec PowerPoint'],'prerequisites':['Savoir utiliser un ordinateur'],'includes':['Exercices pratiques','Templates','Support de cours'],'whatYouWillLearn':'Utiliser les outils bureautiques pour etre plus productif au travail.'}
]
for formation in formations:
    data=json.dumps(formation).encode('utf-8')
    req=urllib.request.Request(base, data=data, headers=headers, method='POST')
    try:
        res=urllib.request.urlopen(req)
        body=json.load(res)
        print('CREATED', body.get('id'), body.get('title'))
    except urllib.error.HTTPError as e:
        print('ERROR', e.code, e.read().decode())
